<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TdpGis.AdminApplication\TdpGis.AdminApplication.csproj" />
    <ProjectReference Include="..\TdpGis.Domain\TdpGis.Domain.csproj" />
    <ProjectReference Include="..\TdpGis.Infrastructure\TdpGis.Infrastructure.csproj" />
  </ItemGroup>

</Project>
