// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TdpGis.ApplicationDb.Database;

#nullable disable

namespace TdpGis.ApplicationDb.Migrations
{
    [DbContext(typeof(GisAppDbContext))]
    partial class GisAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TdpGis.Models.DataSourceSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DatabaseType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DataSourceSettings", (string)null);
                });

            modelBuilder.Entity("TdpGis.Models.GisConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeometryType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("GisWorkspaceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QueryField")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceId");

                    b.HasIndex("GisWorkspaceId");

                    b.ToTable("GisConnections", (string)null);
                });

            modelBuilder.Entity("TdpGis.Models.GisWorkspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GisWorkspaces", (string)null);
                });

            modelBuilder.Entity("TdpGis.Models.GisWorkspaceAccessToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("ExpiredDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GisWorkspaceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AccessToken")
                        .IsUnique();

                    b.HasIndex("GisWorkspaceId");

                    b.ToTable("GisWorkspaceAccessTokens", (string)null);
                });

            modelBuilder.Entity("TdpGis.Models.PropertyMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ColumnType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GisConnectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PropertyLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GisConnectionId");

                    b.ToTable("PropertyMappings", (string)null);
                });

            modelBuilder.Entity("TdpGis.Models.GisConnection", b =>
                {
                    b.HasOne("TdpGis.Models.DataSourceSetting", "DataSource")
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TdpGis.Models.GisWorkspace", "GisWorkspace")
                        .WithMany("Entities")
                        .HasForeignKey("GisWorkspaceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DataSource");

                    b.Navigation("GisWorkspace");
                });

            modelBuilder.Entity("TdpGis.Models.GisWorkspaceAccessToken", b =>
                {
                    b.HasOne("TdpGis.Models.GisWorkspace", "GisWorkspace")
                        .WithMany("AccessTokens")
                        .HasForeignKey("GisWorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GisWorkspace");
                });

            modelBuilder.Entity("TdpGis.Models.PropertyMapping", b =>
                {
                    b.HasOne("TdpGis.Models.GisConnection", null)
                        .WithMany("PropertyMappings")
                        .HasForeignKey("GisConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TdpGis.Models.GisConnection", b =>
                {
                    b.Navigation("PropertyMappings");
                });

            modelBuilder.Entity("TdpGis.Models.GisWorkspace", b =>
                {
                    b.Navigation("AccessTokens");

                    b.Navigation("Entities");
                });
#pragma warning restore 612, 618
        }
    }
}
