// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TdpGis.Infrastructure.Persistence;

#nullable disable

namespace TdpGis.Infrastructure.Migrations
{
    [DbContext(typeof(GisAppDbContext))]
    [Migration("20260405155109_DataProtectionKeys")]
    partial class DataProtectionKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("TdpGis.Domain.DataSourceSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DatabaseType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataSourceSettings", (string)null);
                });

            modelBuilder.Entity("TdpGis.Domain.GisConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityLabel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GeometryType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("GisWorkspaceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QueryField")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceId");

                    b.HasIndex("GisWorkspaceId");

                    b.ToTable("GisConnections", (string)null);
                });

            modelBuilder.Entity("TdpGis.Domain.GisWorkspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GisWorkspaces", (string)null);
                });

            modelBuilder.Entity("TdpGis.Domain.GisWorkspaceAccessToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("ExpiredDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GisWorkspaceId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AccessToken")
                        .IsUnique();

                    b.HasIndex("GisWorkspaceId");

                    b.ToTable("GisWorkspaceAccessTokens", (string)null);
                });

            modelBuilder.Entity("TdpGis.Domain.PropertyMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ColumnType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GisConnectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("PropertyLabel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GisConnectionId");

                    b.ToTable("PropertyMappings", (string)null);
                });

            modelBuilder.Entity("TdpGis.Domain.GisConnection", b =>
                {
                    b.HasOne("TdpGis.Domain.DataSourceSetting", "DataSource")
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TdpGis.Domain.GisWorkspace", "GisWorkspace")
                        .WithMany("Entities")
                        .HasForeignKey("GisWorkspaceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DataSource");

                    b.Navigation("GisWorkspace");
                });

            modelBuilder.Entity("TdpGis.Domain.GisWorkspaceAccessToken", b =>
                {
                    b.HasOne("TdpGis.Domain.GisWorkspace", "GisWorkspace")
                        .WithMany("AccessTokens")
                        .HasForeignKey("GisWorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GisWorkspace");
                });

            modelBuilder.Entity("TdpGis.Domain.PropertyMapping", b =>
                {
                    b.HasOne("TdpGis.Domain.GisConnection", null)
                        .WithMany("PropertyMappings")
                        .HasForeignKey("GisConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TdpGis.Domain.GisConnection", b =>
                {
                    b.Navigation("PropertyMappings");
                });

            modelBuilder.Entity("TdpGis.Domain.GisWorkspace", b =>
                {
                    b.Navigation("AccessTokens");

                    b.Navigation("Entities");
                });
#pragma warning restore 612, 618
        }
    }
}
